main: net.tfminecraft.advancedgunpowder.GunpowderMain
api-version: '1.21.10'
name: AdvancedGunpowder
version: ${project.version}
author: Drefvelin

depend: [MMOCore, MMOItems, MythicLib]

commands:
  agp:
      useage: /<command>
      description: Advanced Gunpowder Command